apiVersion: apps/v1
kind: Deployment
metadata:
  name: finmindworkflow3
  labels:
    app: finmindworkflow3
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1724752196146
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finmindworkflow3
  template:
    metadata:
      labels:
        app: finmindworkflow3
    spec:
      containers:
        - name: finmindworkflow3
          image: finbotreg.azurecr.io/image-workflow-1724752196146-img:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
