apiVersion: v1
kind: Service
metadata:
  name: finmindworkflow3
  namespace: namespace-workflow-1724752196146
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: finmindworkflow3
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000