apiVersion: v1
kind: Service
metadata:
  name: finmindworkflow2
  namespace: namespace-workflow-1724751801093
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: finmindworkflow2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000