apiVersion: v1
kind: Service
metadata:
  name: finmindworkflow
  namespace: namespace-workflow-1724751141501
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: finmindworkflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000